
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author J$
 */
public class Home_Hosteler extends javax.swing.JFrame {

    /**
     * Creates new form Home_Hosteler
     */
    public Home_Hosteler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExitHome = new javax.swing.JButton();
        jButtonMinimize = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jButtonAllLivingStudents = new javax.swing.JButton();
        jButtonAllWorkingEmployees = new javax.swing.JButton();
        jButtonServices = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExitHome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExitHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        jButtonExitHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitHomeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExitHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, -1, -1));

        jButtonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Minimize (1).png"))); // NOI18N
        jButtonMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, -1, -1));

        jButtonLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        jButtonAllLivingStudents.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAllLivingStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotel (1).png"))); // NOI18N
        jButtonAllLivingStudents.setText("All Living Students");
        jButtonAllLivingStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllLivingStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAllLivingStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 257, -1));

        jButtonAllWorkingEmployees.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAllWorkingEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all student living.png"))); // NOI18N
        jButtonAllWorkingEmployees.setText("All Working Employees");
        jButtonAllWorkingEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllWorkingEmployeesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAllWorkingEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 257, -1));

        jButtonServices.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonServices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/services.png"))); // NOI18N
        jButtonServices.setText("Services & Facilities");
        jButtonServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServicesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 257, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home background 4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitHomeActionPerformed
        // Exist Button (Home Page)

        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Exit","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonExitHomeActionPerformed

    private void jButtonMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizeActionPerformed
        // Minimize Button

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizeActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // LogOut Button

        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new LoginPage_Hosteler().setVisible(true);
        }
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonAllLivingStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllLivingStudentsActionPerformed
        // All Living Students (Button)

        jButtonAllLivingStudents.setForeground(Color.red);
        jButtonAllLivingStudents.setBackground(new Color(255,255,255));

        new AllLivingStudents().setVisible(true);
    }//GEN-LAST:event_jButtonAllLivingStudentsActionPerformed

    private void jButtonAllWorkingEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllWorkingEmployeesActionPerformed
        // All Working Employees (Button)

        jButtonAllWorkingEmployees.setForeground(Color.red);
        jButtonAllWorkingEmployees.setBackground(new Color(255,255,255));

        new AllWorkingEmployees().setVisible(true);
    }//GEN-LAST:event_jButtonAllWorkingEmployeesActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
         // Button Color will be Changed when Clicked
         
        jButtonAllLivingStudents.setForeground(new JButton().getForeground());
        jButtonAllLivingStudents.setBackground(new JButton().getBackground());
        
        jButtonServices.setForeground(new JButton().getForeground());
        jButtonServices.setBackground(new JButton().getBackground());
        
        
        jButtonAllWorkingEmployees.setForeground(new JButton().getForeground());
        jButtonAllWorkingEmployees.setBackground(new JButton().getBackground());
        
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButtonServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServicesActionPerformed
        // Services & Facilities (Button)
        
        jButtonServices.setForeground(Color.red);
        jButtonServices.setBackground(new Color(255,255,255));
        
            Facilities_Hosteler fh = new Facilities_Hosteler();
            fh.setVisible(true);
    }//GEN-LAST:event_jButtonServicesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Hosteler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Hosteler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Hosteler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Hosteler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Hosteler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAllLivingStudents;
    private javax.swing.JButton jButtonAllWorkingEmployees;
    private javax.swing.JButton jButtonExitHome;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonMinimize;
    private javax.swing.JButton jButtonServices;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
