
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author J$
 */
public class Home_Warden extends javax.swing.JFrame {

    /**
     * Creates new form Home_Warden
     */
    public Home_Warden() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogOut = new javax.swing.JButton();
        jButtonMinimize = new javax.swing.JButton();
        jButtonExitHome = new javax.swing.JButton();
        jButtonManageRoom = new javax.swing.JButton();
        jButtonNewStudent = new javax.swing.JButton();
        jButtonUpdateDeleteStudents = new javax.swing.JButton();
        jButtonAllLivingStudents = new javax.swing.JButton();
        jButtonLeavedStudent = new javax.swing.JButton();
        jButtonNewEmployee = new javax.swing.JButton();
        jButtonUpdateDeleteEmployee = new javax.swing.JButton();
        jButtonAllWorkingEmployees = new javax.swing.JButton();
        jButtonLeavedEmployees = new javax.swing.JButton();
        jButtonAllVisitors = new javax.swing.JButton();
        jButtonAddVisitor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        jButtonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Minimize (1).png"))); // NOI18N
        jButtonMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, -1, -1));

        jButtonExitHome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExitHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        jButtonExitHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitHomeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExitHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, -1, -1));

        jButtonManageRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonManageRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/room.png"))); // NOI18N
        jButtonManageRoom.setText("Manage Rooms");
        jButtonManageRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManageRoomActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonManageRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 257, -1));

        jButtonNewStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNewStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new student.png"))); // NOI18N
        jButtonNewStudent.setText("New Student");
        jButtonNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewStudentActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 257, -1));

        jButtonUpdateDeleteStudents.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateDeleteStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search student.png"))); // NOI18N
        jButtonUpdateDeleteStudents.setText("Update & Delete Students");
        jButtonUpdateDeleteStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateDeleteStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdateDeleteStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 257, -1));

        jButtonAllLivingStudents.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAllLivingStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotel (1).png"))); // NOI18N
        jButtonAllLivingStudents.setText("All Living Students");
        jButtonAllLivingStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllLivingStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAllLivingStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 257, -1));

        jButtonLeavedStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLeavedStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Leaved students.png"))); // NOI18N
        jButtonLeavedStudent.setText("Left Students");
        jButtonLeavedStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeavedStudentActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLeavedStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 257, -1));

        jButtonNewEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNewEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newEmployee (1).png"))); // NOI18N
        jButtonNewEmployee.setText("New Employee");
        jButtonNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNewEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 257, -1));

        jButtonUpdateDeleteEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateDeleteEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateEmp.png"))); // NOI18N
        jButtonUpdateDeleteEmployee.setText("Update & Delete Employees");
        jButtonUpdateDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateDeleteEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdateDeleteEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        jButtonAllWorkingEmployees.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAllWorkingEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all student living.png"))); // NOI18N
        jButtonAllWorkingEmployees.setText("All Working Employees");
        jButtonAllWorkingEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllWorkingEmployeesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAllWorkingEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 257, -1));

        jButtonLeavedEmployees.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLeavedEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leavedEmployee.png"))); // NOI18N
        jButtonLeavedEmployees.setText("Left Employees");
        jButtonLeavedEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeavedEmployeesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLeavedEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 257, -1));

        jButtonAllVisitors.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAllVisitors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Visitor.png"))); // NOI18N
        jButtonAllVisitors.setText("All Visitors");
        jButtonAllVisitors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllVisitorsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAllVisitors, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 257, 40));

        jButtonAddVisitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddVisitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/QuestionMan.png"))); // NOI18N
        jButtonAddVisitor.setText("Add Visitor");
        jButtonAddVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddVisitorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddVisitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 257, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home background 3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
     
    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // LogOut Button

        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new LoginPage_Warden().setVisible(true);
        }
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizeActionPerformed
        // Minimize Button

        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jButtonMinimizeActionPerformed

    private void jButtonExitHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitHomeActionPerformed
        // Exist Button (Home Page)

        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Exit","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonExitHomeActionPerformed

    private void jButtonManageRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageRoomActionPerformed
        // Manage Room (Button)

        jButtonManageRoom.setForeground(Color.red);
        jButtonManageRoom.setBackground(new Color(255,255,255));

        new ManageRooms().setVisible(true);
    }//GEN-LAST:event_jButtonManageRoomActionPerformed

    private void jButtonNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewStudentActionPerformed
        // New Student (Button)

        jButtonNewStudent.setForeground(Color.red);
        jButtonNewStudent.setBackground(new Color(255,255,255));

        new NewStudent().setVisible(true);
    }//GEN-LAST:event_jButtonNewStudentActionPerformed

    private void jButtonUpdateDeleteStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateDeleteStudentsActionPerformed
        // Update & Delete Students (Button)

        jButtonUpdateDeleteStudents.setForeground(Color.red);
        jButtonUpdateDeleteStudents.setBackground(new Color(255,255,255));

        new UpdateDeleteStudents().setVisible(true);
    }//GEN-LAST:event_jButtonUpdateDeleteStudentsActionPerformed

    private void jButtonAllLivingStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllLivingStudentsActionPerformed
        // All Living Students (Button)

        jButtonAllLivingStudents.setForeground(Color.red);
        jButtonAllLivingStudents.setBackground(new Color(255,255,255));

        new AllLivingStudents().setVisible(true);
    }//GEN-LAST:event_jButtonAllLivingStudentsActionPerformed

    private void jButtonLeavedStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeavedStudentActionPerformed
        // Leaved Student (Button)

        jButtonLeavedStudent.setForeground(Color.red);
        jButtonLeavedStudent.setBackground(new Color(255,255,255));

        new LeftStudents().setVisible(true);
    }//GEN-LAST:event_jButtonLeavedStudentActionPerformed

    private void jButtonNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewEmployeeActionPerformed
        // New Employee (Button)

        jButtonNewEmployee.setForeground(Color.red);
        jButtonNewEmployee.setBackground(new Color(255,255,255));

        new NewEmployee().setVisible(true);
    }//GEN-LAST:event_jButtonNewEmployeeActionPerformed

    private void jButtonUpdateDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateDeleteEmployeeActionPerformed
        // Update And Delete Employee (Button)

        jButtonUpdateDeleteEmployee.setForeground(Color.red);
        jButtonUpdateDeleteEmployee.setBackground(new Color(255,255,255));

        new UpdateDeleteEmployee().setVisible(true);
    }//GEN-LAST:event_jButtonUpdateDeleteEmployeeActionPerformed

    private void jButtonAllWorkingEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllWorkingEmployeesActionPerformed
        // All Working Employees (Button)

        jButtonAllWorkingEmployees.setForeground(Color.red);
        jButtonAllWorkingEmployees.setBackground(new Color(255,255,255));

        new AllWorkingEmployees().setVisible(true);
    }//GEN-LAST:event_jButtonAllWorkingEmployeesActionPerformed

    private void jButtonLeavedEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeavedEmployeesActionPerformed
        // Leaved Students (Button)

        jButtonLeavedEmployees.setForeground(Color.red);
        jButtonLeavedEmployees.setBackground(new Color(255,255,255));

        new LeftEmployees().setVisible(true);
    }//GEN-LAST:event_jButtonLeavedEmployeesActionPerformed

    private void jButtonAllVisitorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllVisitorsActionPerformed
        // All Visitors (Button)
        
        jButtonAllVisitors.setForeground(Color.red);
        jButtonAllVisitors.setBackground(new Color(255,255,255));

        new AllVisitors().setVisible(true);
        
    }//GEN-LAST:event_jButtonAllVisitorsActionPerformed

    private void jButtonAddVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddVisitorActionPerformed
        // Add Visitors (Button)
        
        jButtonAddVisitor.setForeground(Color.red);
        jButtonAddVisitor.setBackground(new Color(255,255,255));

        new AddVisitor().setVisible(true);
        
    }//GEN-LAST:event_jButtonAddVisitorActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // Button Color will be Changed when Clicked
        
        jButtonManageRoom.setForeground(new JButton().getForeground());
        jButtonManageRoom.setBackground(new JButton().getBackground());
        
        jButtonNewStudent.setForeground(new JButton().getForeground());
        jButtonNewStudent.setBackground(new JButton().getBackground());
        
        jButtonUpdateDeleteStudents.setForeground(new JButton().getForeground());
        jButtonUpdateDeleteStudents.setBackground(new JButton().getBackground());
        
        jButtonAllLivingStudents.setForeground(new JButton().getForeground());
        jButtonAllLivingStudents.setBackground(new JButton().getBackground());
        
        jButtonLeavedStudent.setForeground(new JButton().getForeground());
        jButtonLeavedStudent.setBackground(new JButton().getBackground());
        
        jButtonNewEmployee.setForeground(new JButton().getForeground());
        jButtonNewEmployee.setBackground(new JButton().getBackground());
        
        jButtonUpdateDeleteEmployee.setForeground(new JButton().getForeground());
        jButtonUpdateDeleteEmployee.setBackground(new JButton().getBackground());
        
        jButtonAllWorkingEmployees.setForeground(new JButton().getForeground());
        jButtonAllWorkingEmployees.setBackground(new JButton().getBackground());
        
        jButtonLeavedEmployees.setForeground(new JButton().getForeground());
        jButtonLeavedEmployees.setBackground(new JButton().getBackground());
        
        jButtonAddVisitor.setForeground(new JButton().getForeground());
        jButtonAddVisitor.setBackground(new JButton().getBackground());
        
        jButtonAllVisitors.setForeground(new JButton().getForeground());
        jButtonAllVisitors.setBackground(new JButton().getBackground());
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Warden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddVisitor;
    private javax.swing.JButton jButtonAllLivingStudents;
    private javax.swing.JButton jButtonAllVisitors;
    private javax.swing.JButton jButtonAllWorkingEmployees;
    private javax.swing.JButton jButtonExitHome;
    private javax.swing.JButton jButtonLeavedEmployees;
    private javax.swing.JButton jButtonLeavedStudent;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonManageRoom;
    private javax.swing.JButton jButtonMinimize;
    private javax.swing.JButton jButtonNewEmployee;
    private javax.swing.JButton jButtonNewStudent;
    private javax.swing.JButton jButtonUpdateDeleteEmployee;
    private javax.swing.JButton jButtonUpdateDeleteStudents;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
